Webpage/myproject/main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', showhome, name='showhome'),
    path('resultall/', showresultall, name='showresultall'),
    path('result/<str:id>', showdetail, name='showdetail'),
    # path('sort/', showsort, name='showsort'),

]

Webpage/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    # path('users/', include('users.urls')),
]

Webpage/myproject/main/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from re import A
from django.db import models
import random
from django.contrib.auth.models import User


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Data(models.Model):
    id = models.BigIntegerField(primary_key=True)
    # saver = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField(blank=True, null=True)
    sort_x = models.TextField(blank=True, null=True)
    menu_x = models.TextField(blank=True, null=True)
    naver_review_list = models.TextField(blank=True, null=True)
    img_food = models.TextField(blank=True, null=True)
    img_inner = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    sort_y = models.TextField(blank=True, null=True)
    kakao_review_list = models.TextField(blank=True, null=True)
    total_score = models.FloatField(blank=True, null=True)
    total_review_count = models.BigIntegerField(blank=True, null=True)
    category = models.BigIntegerField(blank=True, null=True)
    cluster = models.BigIntegerField(blank=True, null=True)
    review_score = models.FloatField(blank=True, null=True)
    region_code = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data'
    
    # 결과 페이지에서 첫번째 리뷰만 보여주기
    def review_summary(self):
        if self.naver_review_list:
            if '/' in self.naver_review_list:
                review = self.naver_review_list.split('/')[0]
                if len(review) > 160:
                    review = review[:160] + "..."
                return review
        else:
            return self.naver_review_list
    
    # 상세 페이지에서 네이버 리뷰 보여주기
    def naver_review(self):
        if self.naver_review_list:
            if '/' in self.naver_review_list:
                return self.naver_review_list.split('/')
        else:
            return ''
    
    # 상세 페이지에서 카카오 리뷰 보여주기
    def kakao_review(self):
        if self.kakao_review_list:
            if '/' in self.kakao_review_list:
                return self.kakao_review_list.split('/')
        else:
            return ''
    
    # 음식점 내부 이미지 반복출력 위해 split 후 리스트로 반환
    def img_summary(self):
        if self.img_inner:
            if ',' in self.img_inner:
                return random.choice(self.img_inner.split(','))

    # 음식점 대표 음식 이미지
    def food_summary(self):
        if self.img_food:
            if ',' in self.img_food:
                return self.img_food.split(',')[0]
    
    # 음식점 음식 이미지 반복출력
    def food_list(self):
        if self.img_food:
            if ',' in self.img_food:
                return self.img_food.split(',')
        else:
            return "../static/assets/img/img_nothing.jpeg"
    
    # 음식점 내부 이미지 반복출력
    def rest_list(self):
        if self.img_inner:
            if ',' in self.img_inner:
                return self.img_inner.split(',')
        else:
            return "../static/assets/img/img_nothing.jpeg"
    
    # total score 100%로 표시
    def total_score_(self):
        return int(self.total_score) * 20


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class MainData(models.Model):
    id = models.BigIntegerField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    sort_x = models.TextField(blank=True, null=True)
    menu_x = models.TextField(blank=True, null=True)
    naver_review_list = models.TextField(blank=True, null=True)
    img_food = models.TextField(blank=True, null=True)
    img_inner = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    sort_y = models.TextField(blank=True, null=True)
    kakao_review_list = models.TextField(blank=True, null=True)
    total_score = models.FloatField(blank=True, null=True)
    total_review_count = models.BigIntegerField(blank=True, null=True)
    category = models.BigIntegerField(blank=True, null=True)
    cluster = models.BigIntegerField(blank=True, null=True)
    review_score = models.FloatField(blank=True, null=True)
    region_code = models.BigIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_data'

Webpage/myproject/main/forms.py
from django import forms

class RestaurantForm(forms.Form):
    sido = forms.CharField()
    sigugun = forms.CharField()
    img = forms.IntegerField()
    food = forms.CharField()

# class RestaurantForm:
#     def __init__(self, sido, sigugun, img, food):
#         self.sido = sido
#         self.sigugun = sigugun
#         self.img = img
#         self.food = food

Webpage/myproject/main/views.py
from gettext import GNUTranslations
import re
from tkinter import Pack
from unicodedata import name
from django.shortcuts import render, get_object_or_404, redirect
from sqlalchemy import null
from .models import Data
from django import template
from .forms import RestaurantForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def showhome(request):
    cluster_img = []  
    for i in range(5):
        cluster_img.append(Data.objects.filter(cluster=i).first())
    return render(request, 'main/01_inflow_page.html', {'cluster_imgs':cluster_img})

def showresultall(request):

    if request.method=='GET':
        sido = request.GET.get('sido')
        sigugun = request.GET.get('sigugun')
        img = request.GET.get('inner_img')
        food = request.GET.get('food')

        # new_form = RestaurantForm()
        # new_form.sido = sido
        # new_form.sigugun = sigugun
        # new_form.img = img
        # new_form.food = food
        
        if sigugun == '':
            address = ''
            restaurant_address = Data.objects.all()
        else:
            address = int(str(sido) + str(sigugun))
            restaurant_address = Data.objects.filter(region_code = address)
        if food == '전체':
            restaurant_food = Data.objects.all()
        else:
            restaurant_food = Data.objects.filter(category = int(food))
        if img == None:
            restaurant_img = Data.objects.all()
        else:
            restaurant_img = Data.objects.filter(cluster = int(img))
        
        restaurant = (restaurant_address & restaurant_food & restaurant_img).order_by('-total_score','-review_score')
        length = len(restaurant)
        paginator = Paginator(restaurant, 10)
        pagnum = request.GET.get('page')
        restaurant = paginator.get_page(pagnum)

        context = {'restaurant':restaurant, 'length':length}
        return render(request, 'main/02_result_page.html', context)

# def showsort(request):

#     if request.method == "POST":

#         sort = request.POST.get('sort')

#         data = RestaurantForm
#         print(data)
#         sido = data.sido
#         sigugun = data.sigugun
#         img = data.img
#         food = data.food


def showdetail(request,id):
    restaurant = get_object_or_404(Data, pk=id)
    return render(request, 'main/03_detail_page.html', {'restaurant':restaurant})

Webpage/myproject/main/templates/main/02_result_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MUDSIL</title>
        <link rel="icon" type="image/x-icon" href="../static/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../static/css/02_result_page.css" rel="stylesheet" />
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="../static/02_result_page.js"></script>
        <!-- JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
                integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        

        {% csrf_token %} 
        <script type="text/javascript">
        // using jQuery
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        </script>

    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'main:showhome' %}">MUDSIL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:showhome' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="https://github.com/assayw119/Trend_Analysis_and_Recommendation_System_Project" target="_blank">About</a></li>
                        
                        <li class="nav-item dropdown">
                            {% if user.is_authenticated %}
                            <!-- 로그인시 보이는 화면 -->
                            <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{user.username}}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'account_logout' %}">로그아웃</a></li>
                                <li><a class="dropdown-item" href="#">MyPage</a></li>
                            </ul>
                            {% else %}
                            <!-- 로그아웃시 보이는 화면 -->
                            <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Login
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'account_login' %}">로그인</a></li>
                                <li><a class="dropdown-item" href="{% url 'account_signup' %}">회원가입</a></li>
                            </ul>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../static/assets/img/home-bg.png')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>오늘 먹어야 할 음식은?</h1>
                            <span class="subheading">{{length}}개의 결과가 나왔습니다.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="mb-5" style="float: center;">
                        <button class="btn btn-outline-dark flex-shrink-0" onclick="history.back()" style="margin-right: 10px;">
                            처음으로
                        </button>
                        <!-- <select name="sort" id="sort" class="form-select mb-5 text-center" style=" width: 200px; float:right;">
                            <option selected>정렬 기준</option>>
                            <option value="total_score">평점 높은 순</option>>
                            <option value="review_score">긍정 높은 순</option>>
                            <option value="total_review_count">리뷰 많은 순</option>>
                        </select>
                        <button type="submit">테스트</button> -->
                    </div>                 
                    <div id="restaurant-box" class="post-preview">
                        {% for info in restaurant %}
                        <h2 class="post-title" style="left;" name="name">{{info.name}}</h2>
                        <a href="{% url 'main:showdetail' info.id %}">
                            <div class="progress" style="margin: 20px;">
                                <div class="progress-bar" role="progressbar" aria-valuenow="{{info.review_score}}" aria-valuemin="0" aria-valuemax="100" style="width: {{info.review_score}}%">Positive</div>
                            </div>
                            {% if info.img_food == None %}
                            <img src= "../static/assets/img/img_nothing.jpeg"
                                class="food-img" style="float:left;">
                            {% else %}
                            <img src= "{{info.food_summary}}"
                                class="food-img" style="float:left;">
                            {% endif %}
                            <h3 class="post-score" style="float:right">평점: {{info.total_score}}</h3>
                            <h3 class="post-address" name="address">{{info.address}}</h3>

                            <p class="post-review">
                                {{info.review_summary}}
                            </p>
                        </a>
                        
                        <!-- Divider-->
                        <hr class="my-6" />
                        {% endfor %}
                    </div>
                    <!-- Scroll to Top Button-->
                    <div style="float: right;" >
                        <a class="scroll-to-top rounded" href="#page-top">
                            <i class="fas fa-angle-up">Top</i>
                        </a>
                    </div>
                    <!-- Pagination -->
                    {% if restaurant.has_previous %}
                    <a href="&page=1">첫 페이지</a>
                    <a href="&page={{restaurant.previous_page_number}}">이전 페이지</a>
                    {% endif %}

                    <span> {{restaurant.number}} </span>
                    <span> / </span>
                    <span> {{restaurant.paginator.num_pages}} </span>

                    {% if restaurant.has_next %}
                    <a href="{# csrf_token #}&page={{restaurant.next_page_number}}">다음 페이지</a>
                    <a href="&page={{restaurant.paginator.num_pages}}">마지막 페이지</a>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://github.com/assayw119/Trend_Analysis_and_Recommendation_System_Project" target="_blank">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">2022-1 DataScience Capston Design</div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>